Introduce tryexpand but not working due to path resolution
test pass ... FAILED

failures:

---- pass stdout ----
Running 1 macro expansion tests from tests/entry.rs:3:5 ...

tests/add/single_ident.rs - ERROR
--------------------------
Unexpected failure!

SOURCE:

extern crate short_vis_path;

mod procfs {
    #![short_vis_path::add(procfs)]

    pub(in procfs) fn foo() {}
}

fn main() {
    procfs::foo()
}

EXPANDED:

extern crate short_vis_path;
fn main() {
    procfs::foo()
}

ERROR:

error: custom attribute panicked
 --> /tests/add/single_ident.rs:8:5
  |
8 |     #![short_vis_path::add(procfs)]
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: message: "/target/tests/<CRATE>" must be a prefix of "/tests/add/single_ident.rs".
error[E0433]: failed to resolve: use of unresolved module or unlinked crate `procfs`
  --> /tests/add/single_ident.rs:14:5
   |
14 |     procfs::foo()
   |     ^^^^^^ use of unresolved module or unlinked crate `procfs`
   |
   = help: if you wanted to use a crate named `procfs`, use `cargo add procfs` to add it to your `Cargo.toml`
For more information about this error, try `rustc --explain E0433`.
error: could not compile `<CRATE>` (bin "<BIN>") due to 2 previous errors
--------------------------

thread 'pass' (130570) panicked at /home/zjp/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tryexpand-0.13.0/src/test_suite.rs:84
8:20:

1 of 1 tests failed:

    tests/add/single_ident.rs

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    pass